### PR TITLE
Reading BG values from history & clean teardown of pump connection (2nd attempt)

### PR DESCRIPTION
**Pull request by paulokow**
Hi,

Based on @pazaan implementation in tidepool-org/chrome-uploader I ported first implementation of download of the pump history, right now supporting only BG Values

Also made a bit of refactoring in the main routine, so that connection build-up and safe teardown is placed in downloadPumpSession(), while custom functionality is passed as a reference (pumpDownload).
Added also all the commands for clean exit and close of pump connection.

Also added a check if 0x81 responses are really these expected (sometimes they aren't!).

### CODE REVIEW

**Comment by paulokow** [comment]
@pazaan, did you have time to review this PR ?

**Comment by pazaan** [comment]
Hey @paulokow. Just got back for a long OS trip without access to devices. Will take a look this weekend.

**Comment by pazaan** [comment]
@paulokow Thanks for this incredible contribution! Would you be interested in being a direct contributor to this repo?

**Comment by paulokow** [comment]
Hi @pazaan , I'll be honoured to be a direct contributor.

**Pull request merged**
